// @ts-check
// 3.4.0에서 더한 백그라운드 알림 문구. {n}·{v}는 숫자로 바꾼다. 없는 언어는 영어로 보낸다.

export const ALERT_TEXT = {
  ko: {
    econSoon: '{n}분 후 발표',
    quietSummary: '방해 금지 시간 동안 알림 {n}건',
    surgeUp: '{n}분 급등',
    surgeDown: '{n}분 급락',
    marketWarning: '업비트 시장경보',
    WARNING: '유의 종목 지정',
    PRICE_FLUCTUATIONS: '가격 급등락',
    TRADING_VOLUME_SOARING: '거래량 급등',
    DEPOSIT_AMOUNT_SOARING: '입금량 급등',
    GLOBAL_PRICE_DIFFERENCES: '글로벌 시세 차이',
    CONCENTRATION_OF_SMALL_ACCOUNTS: '소수 계정 거래 집중',
    exchangeNotice: '거래 공지',
    oiChange: '미결제약정 1시간 {v}',
    whaleBuy: '대량 매수 체결',
    whaleSell: '대량 매도 체결',
  },
  en: {
    econSoon: 'Due in {n} min',
    quietSummary: '{n} alerts during quiet hours',
    surgeUp: '{n}-min surge',
    surgeDown: '{n}-min drop',
    marketWarning: 'Upbit market alert',
    WARNING: 'Investment warning',
    PRICE_FLUCTUATIONS: 'Sharp price swing',
    TRADING_VOLUME_SOARING: 'Volume spike',
    DEPOSIT_AMOUNT_SOARING: 'Deposit spike',
    GLOBAL_PRICE_DIFFERENCES: 'Gap vs global price',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'Trading concentrated in few accounts',
    exchangeNotice: 'Trading notice',
    oiChange: 'Open interest 1h {v}',
    whaleBuy: 'Large buy',
    whaleSell: 'Large sell',
  },
  es: {
    econSoon: 'En {n} min',
    quietSummary: '{n} alertas durante las horas silenciosas',
    surgeUp: 'Subida en {n} min',
    surgeDown: 'Caída en {n} min',
    marketWarning: 'Alerta de mercado de Upbit',
    WARNING: 'Advertencia de inversión',
    PRICE_FLUCTUATIONS: 'Variación brusca de precio',
    TRADING_VOLUME_SOARING: 'Pico de volumen',
    DEPOSIT_AMOUNT_SOARING: 'Pico de depósitos',
    GLOBAL_PRICE_DIFFERENCES: 'Diferencia con el precio global',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'Operaciones concentradas en pocas cuentas',
    exchangeNotice: 'Aviso de trading',
    oiChange: 'Interés abierto 1 h {v}',
    whaleBuy: 'Compra grande',
    whaleSell: 'Venta grande',
  },
  pt: {
    econSoon: 'Em {n} min',
    quietSummary: '{n} alertas durante o horário silencioso',
    surgeUp: 'Alta em {n} min',
    surgeDown: 'Queda em {n} min',
    marketWarning: 'Alerta de mercado da Upbit',
    WARNING: 'Aviso de investimento',
    PRICE_FLUCTUATIONS: 'Oscilação brusca de preço',
    TRADING_VOLUME_SOARING: 'Pico de volume',
    DEPOSIT_AMOUNT_SOARING: 'Pico de depósitos',
    GLOBAL_PRICE_DIFFERENCES: 'Diferença do preço global',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'Negociação concentrada em poucas contas',
    exchangeNotice: 'Aviso de negociação',
    oiChange: 'Contratos em aberto 1 h {v}',
    whaleBuy: 'Compra grande',
    whaleSell: 'Venda grande',
  },
  vi: {
    econSoon: 'Còn {n} phút',
    quietSummary: '{n} cảnh báo trong giờ yên lặng',
    surgeUp: 'Tăng mạnh trong {n} phút',
    surgeDown: 'Giảm mạnh trong {n} phút',
    marketWarning: 'Cảnh báo thị trường Upbit',
    WARNING: 'Cảnh báo đầu tư',
    PRICE_FLUCTUATIONS: 'Giá biến động mạnh',
    TRADING_VOLUME_SOARING: 'Khối lượng tăng đột biến',
    DEPOSIT_AMOUNT_SOARING: 'Lượng nạp tăng đột biến',
    GLOBAL_PRICE_DIFFERENCES: 'Chênh lệch với giá toàn cầu',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'Giao dịch tập trung ở ít tài khoản',
    exchangeNotice: 'Thông báo giao dịch',
    oiChange: 'Hợp đồng mở 1 giờ {v}',
    whaleBuy: 'Lệnh mua lớn',
    whaleSell: 'Lệnh bán lớn',
  },
  tr: {
    econSoon: '{n} dk sonra',
    quietSummary: 'Sessiz saatlerde {n} uyarı',
    surgeUp: '{n} dk içinde sert yükseliş',
    surgeDown: '{n} dk içinde sert düşüş',
    marketWarning: 'Upbit piyasa uyarısı',
    WARNING: 'Yatırım uyarısı',
    PRICE_FLUCTUATIONS: 'Sert fiyat dalgalanması',
    TRADING_VOLUME_SOARING: 'Hacim artışı',
    DEPOSIT_AMOUNT_SOARING: 'Yatırma artışı',
    GLOBAL_PRICE_DIFFERENCES: 'Küresel fiyattan sapma',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'İşlemler az sayıda hesapta yoğun',
    exchangeNotice: 'İşlem duyurusu',
    oiChange: 'Açık pozisyon 1 sa {v}',
    whaleBuy: 'Büyük alım',
    whaleSell: 'Büyük satış',
  },
  id: {
    econSoon: '{n} menit lagi',
    quietSummary: '{n} peringatan selama jam tenang',
    surgeUp: 'Lonjakan {n} menit',
    surgeDown: 'Penurunan {n} menit',
    marketWarning: 'Peringatan pasar Upbit',
    WARNING: 'Peringatan investasi',
    PRICE_FLUCTUATIONS: 'Fluktuasi harga tajam',
    TRADING_VOLUME_SOARING: 'Lonjakan volume',
    DEPOSIT_AMOUNT_SOARING: 'Lonjakan deposit',
    GLOBAL_PRICE_DIFFERENCES: 'Selisih dengan harga global',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'Perdagangan terpusat di sedikit akun',
    exchangeNotice: 'Pengumuman trading',
    oiChange: 'Open interest 1 jam {v}',
    whaleBuy: 'Pembelian besar',
    whaleSell: 'Penjualan besar',
  },
  ja: {
    econSoon: '{n}分後に発表',
    quietSummary: 'おやすみ時間中の通知 {n}件',
    surgeUp: '{n}分間で急騰',
    surgeDown: '{n}分間で急落',
    marketWarning: 'Upbit 市場警報',
    WARNING: '投資注意銘柄に指定',
    PRICE_FLUCTUATIONS: '価格の急変動',
    TRADING_VOLUME_SOARING: '出来高の急増',
    DEPOSIT_AMOUNT_SOARING: '入金量の急増',
    GLOBAL_PRICE_DIFFERENCES: '海外相場との乖離',
    CONCENTRATION_OF_SMALL_ACCOUNTS: '少数アカウントへの取引集中',
    exchangeNotice: '取引のお知らせ',
    oiChange: '未決済建玉 1時間 {v}',
    whaleBuy: '大口買い約定',
    whaleSell: '大口売り約定',
  },
  zh: {
    econSoon: '{n}分钟后公布',
    quietSummary: '免打扰期间的提醒 {n} 条',
    surgeUp: '{n}分钟急涨',
    surgeDown: '{n}分钟急跌',
    marketWarning: 'Upbit 市场警报',
    WARNING: '被列为投资警示',
    PRICE_FLUCTUATIONS: '价格剧烈波动',
    TRADING_VOLUME_SOARING: '成交量激增',
    DEPOSIT_AMOUNT_SOARING: '充值量激增',
    GLOBAL_PRICE_DIFFERENCES: '与全球价格偏离',
    CONCENTRATION_OF_SMALL_ACCOUNTS: '交易集中于少数账户',
    exchangeNotice: '交易公告',
    oiChange: '未平仓合约 1小时 {v}',
    whaleBuy: '大额买入成交',
    whaleSell: '大额卖出成交',
  },
  hi: {
    econSoon: '{n} मिनट में',
    quietSummary: 'शांत समय में {n} अलर्ट',
    surgeUp: '{n} मिनट में तेज़ उछाल',
    surgeDown: '{n} मिनट में तेज़ गिरावट',
    marketWarning: 'Upbit बाज़ार अलर्ट',
    WARNING: 'निवेश चेतावनी',
    PRICE_FLUCTUATIONS: 'कीमत में तेज़ उतार-चढ़ाव',
    TRADING_VOLUME_SOARING: 'वॉल्यूम में उछाल',
    DEPOSIT_AMOUNT_SOARING: 'जमा में उछाल',
    GLOBAL_PRICE_DIFFERENCES: 'वैश्विक कीमत से अंतर',
    CONCENTRATION_OF_SMALL_ACCOUNTS: 'कुछ खातों में केंद्रित ट्रेडिंग',
    exchangeNotice: 'ट्रेडिंग सूचना',
    oiChange: 'ओपन इंटरेस्ट 1 घंटा {v}',
    whaleBuy: 'बड़ी खरीद',
    whaleSell: 'बड़ी बिक्री',
  },
};

/**
 * @param {string} language
 * @param {keyof typeof ALERT_TEXT.en} key
 * @param {Record<string, string | number>} [values]
 */
export function alertText(language, key, values = {}) {
  const table = /** @type {Record<string, Record<string, string>>} */ (ALERT_TEXT);
  const text = table[language]?.[key] ?? ALERT_TEXT.en[key];
  return text.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ''));
}
